/* eslint-disable prettier/prettier */
export enum SCREENS {
  'Splash' = 'Splash',
  'Login' = 'Login',
  'Signup' = 'Signup',
  'Home' = 'Home',
  'Profile' = 'Profile',
  'Settings' = 'Settings',
  'About' = 'About',
  'Dashboard' = 'Dashboard',
  'Chats' = 'Chats',
  'Organ' = 'Organ',
  'Health' = 'Health',
  'Main' = 'Main',

  'EyeScreen' = 'EyeScreen',
  'OrganScreen' = 'OrganScreen',
  'SkinScreen' = 'SkinScreen',
  'BloodScreen' = 'BloodScreen',

  'DoctorOnboard' = 'DoctorOnboard',
  'ResearcherOnboard' = 'ResearcherOnboard',
  'Researcher' = 'Researcher',
  'DocumentAccess' = 'DocumentAccess',
  'TrackHealth' = 'TrackHealth',
  'ResearchFindings' = 'ResearchFindings',
  'Wallet' = 'Wallet',
  'MedicalStore' = 'MedicalStore',
  'ViewRequests' = 'ViewRequests',
}
